---
author: "Liam Pendleton"
date: "2023-11-14"
output: html_document
---

## *Estimating the influence of oceanographic conditions on breeding success of Pigeon Guillemots (Cepphus columba)* 

#### Liam C. Pendleton, Lee Robinson, Eric L. Wagner, Scott F. Pearson, Susan M. Thomas, Sarah J. Converse

##### Please contact Liam Pendleton at pendle@uw.edu for questions about the code or data.

##### Secondary contact: Sarah Converse (sconver@usgs.gov)

________________________________________________________________________________

## Abstract

Seabird population dynamics are tightly linked with conditions in marine foraging habitats. Marine environmental conditions have direct effects on prey abundance and quality and can influence demographic outcomes. We evaluated the influence of marine conditions on breeding success of Pigeon Guillemots (Cepphus columba) using a long-term data set from Protection Island, Washington, USA. The Pigeon Guillemot has been identified as an indicator species in the Puget Sound region, but the relationship between marine conditions and guillemot breeding success is not well understood. We evaluated the effects of sea surface temperature, chlorophyll-a concentration, the Pacific Decadal Oscillation, and the North Pacific Gyre Oscillation on two metrics of breeding success: the probability that a nest produces at least one chick and the probability that a nest produces two chicks, given it produced at least one. We evaluated effects of oceanographic covariates across five temporal scales to identify periods in which particular oceanographic conditions may be most biologically significant. Our results will inform the relationship between marine conditions and Pigeon Guillemot population dynamics, leading to a better understanding of Pigeon Guillemots as an indicator species in Puget Sound.

### Table of Contents

### [Data](./Data)
This folder contains raw data for all of the oceanographic predictors, nest monitoring data, and a file "model_input.csv", which was created and stored from the file "process_nestboxdata.R". Note that there are two files of chlorophyll data that cover two different periods.

### [Scripts](./Scripts)
This is a directory to the different types of scripts used in this project. The "covariates" folder contains the scripts used to process and format each of the oceanographic predictor data sets. The "nestDataPreP" folder contains the script used to determine outcomes of monitored nests. The "nestModels" folder contains five scripts: one to relate each of the four oceanographic predictors to breeding outcomes, and one that includes all of the top-performing temporal variants of the oceanographic predictors (nest_model_allvars.R). Finally, the "results" folder contains a script to process the output of the "nest_model_allvars.R" file found in the "nestModels" folder, and a script to create figures.

### [Results](./Results)
This folder contains a PDF featuring the MCMC trace plots of "nest_model_allvars.R", and the output it produces written into "out.rds".

### Required Packages and Versions Used
xxx

### Details of Article 
Pendleton LC, L Robinson, EL Wagner, SF Pearson, SM Thomas, and SJ Converse. 2024. Estimating the influence of oceanographic conditions on breeding success in Pigeon Guillemots (*Cepphus columba*).

### How to Use this Repository
Despite the variety of files in this repository, only a few are necessary to reproduce the analysis. Begin by running "process_nestboxdata.R" to produce PIGU breeding outcomes. Run "nest_model_allvars.R" to run models. This will automatically run the scripts used to process covariate data. Run "process_results.R" to process and contextualize the output from "nest_model_allvars.R". Finally, run "figures.R" to produce figures.